version: "3.9"
services:
  application:
    container_name: "ntuwu-furry"
    build:
      context: ./
      dockerfile: Dockerfile
    image: "ntuwu-furry-image"
    volumes:
      - ./public:/app/public
    ports:
      - "3000:3000"
